### ISSUE TITLE
Image Pull Failed issue on Mac M1

### ISSUE THREAD

**Issue by michaelwang1994-olo** [bentoml/yatai-deployment#131]
Following the [thread here](https://github.com/bentoml/Yatai/issues/492#issuecomment-1830841612), I got `yatai-deployment` working in the web-ui but ran into this issue when I tried to deploy my bento:

`Failed to pull image "quay.io/bentoml/kaniko:debug": rpc error: code = Unknown desc = no matching manifest for linux/arm64/v8 in the manifest list entries`

I am using:
minikube: v1.31.1
yatai: v1.1.13
yatai-image-builder: v1.2.16
yatai-deployment: v1.1.14
MacOS: Ventura 13.6.2, M1 Max

**Comment by yetone** [comment]
‌‌‌‌Apologies, we currently do not support the ARM architecture. If you are using a Mac M1/M2, we recommend using [orbstack](https://orbstack.dev/) as the container runtime, as it provides good support for the x86 architecture.

**Comment by yetone** [comment]
‌‌‌‌Apologies, the information provided above was incorrect. The issue has now been resolved.
