### ISSUE TITLE
Failed to reconcile BentoDeployment

### ISSUE THREAD

**Issue by aditya624** [bentoml/yatai-deployment#57]
Failed to reconcile BentoDeployment: DoJsonRequest Error: [GET]http://yatai.yatai-system.svc.cluster.local/api/v1/current_org: Get "http://yatai.yatai-system.svc.cluster.local/api/v1/current_org": read tcp 10.244.2.243:46536->10.97.35.56:80: read: connection reset by peer

why alway failed to deploy either ui or cli

**Comment by yetone** [comment]
First, you should follow the documentation to check if the yatai pod is working properly:

https://docs.bentoml.org/projects/yatai/en/latest/installation/yatai.html#verify-the-yatai-installation

If it works properly, then check the network of your k8s cluster:

```bash
kubectl run test-network --rm --tty -i --restart='Never' \
    --namespace default \
    --image yetone/curl \
    --command -- sh -c 'curl http://yatai.yatai-system.svc.cluster.local/api/v1/current_org'
```

The above command should return:

```bash
{"message":"username in cookie is empty"}pod "test-network" deleted
```

**Comment by aditya624** [comment]
i verify the installation,
NAME                     READY   STATUS    RESTARTS   AGE
yatai-56d9c649b5-5wpsl   1/1     Running   0          2d10h

but when i try test-network, Error: ImagePullBackOff

**Comment by yetone** [comment]
@aditya624 which k8s distribution do you use? `k3s`

**Comment by aditya624** [comment]
k8s 

result testing like:
curl: (28) Failed to connect to yatai.yatai-system.svc.cluster.local port 80 after 129553 ms: Connection timed out
pod "test-network" deleted
pod default/test-network terminated (Error)

**Comment by yetone** [comment]
@aditya624 Can you see the `nginx-service` service in `default` namespace?

```bash
kubectl get svc
```

**Comment by aditya624** [comment]
svc nginx already exists.
![Screenshot from 2022-11-30 22-32-48](https://user-images.githubusercontent.com/53865102/204841036-1f20f176-8397-4ddb-aa4c-db63e01fa12c.png)

**Comment by yetone** [comment]
@aditya624

It looks like your `kube-dns` is not working properly, you should check the `kube-dns' component of your k8s cluster.

For example, you can try to restart the `coredns` deployment:

```bash
kubectl -n kube-sytem rollout restart deploy/coredns
```

**Comment by aditya624** [comment]
@yetone i have question.
Can i change the internal url ?

![Screenshot from 2022-12-01 11-01-39](https://user-images.githubusercontent.com/53865102/204962982-cffa3a36-8d3c-41e1-9dc5-cfd3c5fb0468.png)

**Comment by yetone** [comment]
@aditya624 Since this URL is based on `deployment service name` and `namespace`, this URL cannot be changed:

`${deploymentName}.${namespace}.svc.cluster.local`

**Comment by aditya624** [comment]
> First, you should follow the documentation to check if the yatai pod is working properly:
> 
> https://docs.bentoml.org/projects/yatai/en/latest/installation/yatai.html#verify-the-yatai-installation
> 
> If it works properly, then check the network of your k8s cluster:
> 
> ```shell
> kubectl run test-network --rm --tty -i --restart='Never' \
>     --namespace default \
>     --image curlimages/curl \
>     --command -- sh -c 'curl http://yatai.yatai-system.svc.cluster.local/api/v1/current_org'
> ```
> 
> The above command should return:
> 
> ```shell
> {"message":"username in cookie is empty"}pod "test-network" deleted
> ```

I failed to use your command line because it uses svc.cluster.local. however, it works without using the suffix.

do you know the location of the cluster domain settings in k8s ?
i think "curl" failed because k8s domain cluster doesn't match svc.domain.cluster.

**Comment by yetone** [comment]
> > First, you should follow the documentation to check if the yatai pod is working properly:
> > https://docs.bentoml.org/projects/yatai/en/latest/installation/yatai.html#verify-the-yatai-installation
> > If it works properly, then check the network of your k8s cluster:
> > ```shell
> > kubectl run test-network --rm --tty -i --restart='Never' \
> >     --namespace default \
> >     --image curlimages/curl \
> >     --command -- sh -c 'curl http://yatai.yatai-system.svc.cluster.local/api/v1/current_org'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The above command should return:
> > ```shell
> > {"message":"username in cookie is empty"}pod "test-network" deleted
> > ```
> 
> I failed to use your command line because it uses svc.cluster.local. however, it works without using the suffix.
> 
> do you know the location of the cluster domain settings in k8s ? i think "curl" failed because k8s domain cluster doesn't match svc.domain.cluster.

@aditya624 `svc.cluster.local` is the [default cluster domain](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/) for k8s. If it does not work or is changed, you should communicate with your k8s cluster administrator. If you are the k8s cluster administrator, you should debug the cluster DNS following the official documentation: https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

**Comment by aditya624** [comment]
This problem solve. I just change the curl image.
Iam using buildpack-deps:curl

Thank you.
