### ISSUE TITLE
yatai-image-builder is not ready

### ISSUE THREAD

**Issue by maroshmka** [bentoml/yatai-deployment#86]
When using quick-install, some component called yatai-image-builder is being verified - https://github.com/bentoml/yatai-deployment/blob/main/scripts/quick-install-yatai-deployment.sh#L94

Although, nothing installs it (haven't seen it in yatai quickinstal). And I haven't found any mentions in docs.

Is it a bug or am I missing something?

thanks!

**Comment by yetone** [comment]
Sorry, I forgot to [upgrade](https://github.com/bentoml/Yatai/commit/c18952b37732cebe018f0836484aef65db92fac8) the URL of the yatai-deployment installation script, you can now use this command to install yatai-deployment:

```bash
bash <(curl -s "https://raw.githubusercontent.com/bentoml/yatai-deployment/v1.0.x/scripts/quick-install-yatai-deployment.sh")
```

**Comment by maroshmka** [comment]
great, thanks!
